channels:
  - conda-forge
  - defaults
  - cadquery
  - plotly
dependencies:
  - jupyterlab=3.0.10
  - ipywidgets=7.6.3
  - pandas=1.2.3
  - ipygany=0.5.0
  - pyvista=0.29.0
  - panel=0.11.0
  - plotly=4.14.3
  - cadquery=master
  - jupyter-dash=0.3.0
  - networkx=2.5
  - colour=0.1.5
  - cairo=1.16.0
  - ipympl=0.6.3
  - ipyevents=0.8.2
  - ipycanvas=0.8.2
  - dash-bootstrap-components=0.11.3
  - pip=21.2.4
  - pip:
    - ipyvtk_simple==0.1.4
    - jupyter-cadquery==2.0.0
    - dash-vtk==0.0.6
    - dash-treeview-antd==0.0.1