channels:
  - conda-forge
  - defaults
  - cadquery
  - plotly
dependencies:
  - cadquery=master # version 2.1 does not support python 3.9
  - cairo=1.16.0
  - colour=0.1.5
  - dash-bootstrap-components=1.0.3
  - ipycanvas=0.10.2
  - ipyevents=2.0.1
  - ipygany=0.5.0
  - ipympl=0.8.8
  - ipyvtklink==0.2.2
  - ipywidgets=7.6.5
  - jupyterlab=3.2.9
  - networkx=2.6.3
  - pandas=1.4.1
  - panel=0.12.6
  - pip=22.0.3
  - plotly=5.6.0
  - pythreejs=2.3.0
  - pip:
    - pyvista==0.33.3
    - jupyter-cadquery==2.2.1
    - dash-vtk==0.0.9
    - dash-treeview-antd==0.0.1
