channels:
  - conda-forge
  - defaults
  - cadquery
  - plotly
dependencies:
  - jupyterlab=3.2.0
  - ipywidgets=7.6.5
  - pandas=1.2.4
  - ipygany=0.5.0
  - pyvista=0.32.1
  - panel=0.12.4
  - plotly=5.3.1
  - cadquery=master # version 2.1 does not support python 3.9
  - jupyter-dash=0.4.0
  - networkx=2.6.3
  - colour=0.1.5
  - cairo=1.16.0
  - ipympl=0.8.1
  - ipyevents=2.0.1
  - ipycanvas=0.9.0
  - dash-bootstrap-components=1.0.0
  - ipyvtklink==0.2.1
  - pip= 21.3
  - pip:
    - jupyter-cadquery==2.2.1
    - dash-vtk==0.0.9
    - dash-treeview-antd==0.0.1