name: ci

on:
  push:
    tags:
    - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read IMAGE_NAME
        id: image_name
        uses: falti/dotenv-action@v0.2.7 
        with:
          path: IMAGE_NAME
      - name: Login to ${{ steps.image_name.outputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.image_name.outputs.registry }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.image_name.outputs.registry }}/${{ steps.image_name.outputs.repository }}
          github-token: ${{ github.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
